import { describe, it, expect } from 'vitest';
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { ProvidenceRecord } from '@xsoc/shared-types';
import {
  jcs,
  recordDigest,
  recordLine,
  headCommitment,
  anchorMessage,
  keyIdOf,
  checkpointGenesisNonce,
  GENESIS_DIGEST
} from '../src/index.js';

const RAW = readFileSync(new URL('./vectors/guard-providence-v3.json', import.meta.url));
// SHA-256 of the vector file as generated by scripts/gen-providence-v3-vectors.py.
// The same constant is recorded in xsoc-pqc-s3-console-api verify/src/guard.rs, so
// the two checked-in copies cannot drift apart unseen.
const VECTORS_SHA256 = 'a740a8c3b522fc514da9384cb37770a53d5aef2d1350858130a07f519a2c1b2d';
const v = JSON.parse(RAW.toString('utf8'));

describe('guard-providence-v3 known-answer vectors', () => {
  it('the vector file is the recorded one', () => {
    expect(createHash('sha256').update(RAW).digest('hex')).toBe(VECTORS_SHA256);
  });

  it('record digests match, and each line is the line this writer writes', () => {
    v.records.forEach((rec: unknown, i: number) => {
      const r = ProvidenceRecord.parse(rec);
      expect(recordDigest(r).toString('hex')).toBe(v.record_digests[i]);
      expect(recordLine(r)).toBe(v.record_lines[i]);
    });
  });

  it('canonical JSON matches', () => {
    for (const c of v.jcs) expect(jcs(c.value)).toBe(c.jcs);
  });

  it('the head commitment, the empty commitment and the genesis nonce match', () => {
    const head = v.head;
    expect(headCommitment(head.seq, Buffer.from(head.head_digest, 'hex'), head.chain_id).toString('hex')).toBe(v.head_commitment);
    expect(headCommitment(0, GENESIS_DIGEST, head.chain_id).toString('hex')).toBe(v.empty_head_commitment);
    expect(checkpointGenesisNonce().toString('hex')).toBe(v.checkpoint_genesis_nonce);
  });

  it('the anchor message and key id match', () => {
    const a = v.anchor;
    const pk = Buffer.from(a.public_key, 'base64');
    expect(keyIdOf(pk)).toBe(a.key_id);
    expect(anchorMessage(Buffer.from(a.commitment, 'hex'), a.timestamp_ms, a.algorithm, a.key_id, pk).toString('hex')).toBe(v.anchor_message);
  });

  it('under the PQC S3 domain a record digests to the cross-domain vector, not its own', () => {
    const r = ProvidenceRecord.parse(v.records[0]);
    const s3 = recordDigest(r, 'xsoc-pqc-s3:audit-record:v3').toString('hex');
    expect(s3).toBe(v.cross_domain.digest_under_s3_domain);
    expect(s3).not.toBe(v.record_digests[0]);
  });

  it('canonical JSON refuses what has no single encoding', () => {
    expect(() => jcs(1.5)).toThrow();
    expect(() => jcs(2 ** 53)).toThrow();
    expect(() => jcs({ a: undefined })).toThrow();
    expect(() => jcs('\ud800')).toThrow();
    expect(() => jcs(new Date())).toThrow();
    expect(jcs(-0)).toBe('0');
  });
});
